spring:
  application:
    name: company-registry-service

app:
  api:
    company-registry-path: /api/v1/companies/registry
  registry:
    key-separator: "::"

logging:
  level:
    root: INFO
    br.com.client.companyregistry: DEBUG
